### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Jackster35** [vram4/Ogar#112]
Hey vram4, I was just looking in my console and noticed this error:
>buffer.js:419
    throw new RangeError('attempt to write outside buffer bounds');
          ^
RangeError: attempt to write outside buffer bounds
    at Buffer.write (buffer.js:419:11)
    at Sender.send (/home/agarp/node_modules/ws/lib/Sender.hixie.js:54:14)
    at WebSocket.send (/home/agarp/node_modules/ws/lib/WebSocket.js:262:18)
    at WebSocket.sendPacket (/home/agarp/svr1/Ogar/src/GameServer.js:848:14)
    at PlayerTracker.update (/home/agarp/svr1/Ogar/src/PlayerTracker.js:153:17)
    at GameServer.updateClients (/home/agarp/svr1/Ogar/src/GameServer.js:359:39)
    at GameServer.mainLoop (/home/agarp/svr1/Ogar/src/GameServer.js:329:14)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)

(It crashed and restarted via my script)

I'm not sure what caused it but I'm sure you could find it. I believe the server had loads of players at the time.

**Comment by Eureka22** [comment]
Is it updated? Yesterday I met the same problem.

**Comment by Jackster35** [comment]
Yes, latest git pull.
