### ISSUE TITLE
Sometimes spectator can crash Tournament server

### ISSUE THREAD

**Issue by batbug** [vram4/Ogar#118]
/home/ogar4/src/GameServer.js:805
            if (this.clients[oldPlayer].playerTracker.cells.length > 0) {
                                       ^
TypeError: Cannot read property 'playerTracker' of undefined
    at GameServer.switchSpectator (/home/ogar4/src/GameServer.js:805:40)
    at PacketHandler.handleMessage (/home/ogar4/src/PacketHandler.js:57:33)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onbinary (/home/ogar4/node_modules/ws/lib/WebSocket.js:804:10)
    at /home/ogar4/node_modules/ws/lib/Receiver.js:533:18
    at /home/ogar4/node_modules/ws/lib/Receiver.js:357:7
    at /home/ogar4/node_modules/ws/lib/PerMessageDeflate.js:217:5
    at afterWrite (_stream_writable.js:361:3)
    at onwrite (_stream_writable.js:352:7)
    at WritableState.onwrite (_stream_writable.js:105:5)

**Comment by vram4** [comment]
Are you using the latest update?

**Comment by batbug** [comment]
no. like 2 days old. But i dont see any changes in the GameServer.prototype.switchSpectator function with the latest update and this is where error occurs.
