### ISSUE TITLE
Hunger Games crash

### ISSUE THREAD

**Issue by Jackster35** [vram4/Ogar#123]
>/home/agarp/svr3/Ogar/src/GameServer.js:841
            if (this.clients[oldPlayer].playerTracker.cells.length > 0) {
                                       ^
TypeError: Cannot read property 'playerTracker' of undefined
    at GameServer.switchSpectator (/home/agarp/svr3/Ogar/src/GameServer.js:841:40)
    at PacketHandler.handleMessage (/home/agarp/svr3/Ogar/src/PacketHandler.js:57:33)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onbinary (/home/agarp/node_modules/ws/lib/WebSocket.js:804:10)
    at /home/agarp/node_modules/ws/lib/Receiver.js:533:18
    at Receiver.applyExtensions (/home/agarp/node_modules/ws/lib/Receiver.js:360:5)
    at /home/agarp/node_modules/ws/lib/Receiver.js:527:14
    at Receiver.flush (/home/agarp/node_modules/ws/lib/Receiver.js:336:3)
    at Receiver.opcodes.2.finish (/home/agarp/node_modules/ws/lib/Receiver.js:538:12)
    at Receiver.expectHandler (/home/agarp/node_modules/ws/lib/Receiver.js:512:33)

Unsure what could of caused this error, just found it in my console. Might find it of use for patching, vram4.

**Comment by Jackster35** [comment]
Also people are reporting issues of lag. My ram/cpu seams to be stable as well as the process ram/cpu usage. This new bit of code, might also be adding lag for the server.

**Comment by vram4** [comment]
Are you using the latest commit? I fixed this last night.

**Comment by Jackster35** [comment]
I might not be on that server, sorry about that haha

**Comment by vram4** [comment]
As for the lag, what kind was it? If there are alot of cells on the screen (like food), it will lag the client, but the server side will seem find.

**Comment by Jackster35** [comment]
Server lag, it was on both of our Hunger Game servers which are on different machines. And I left the food at default which is statically set in HungerGames.js. I restarted it and it seems fine so far. It might be something that happens over time, I'm not as of yet. I'll see if I can find more information on it my self. So far, I'm going by user reports
