### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by Spurlex** [vram4/Ogar#34]
```
root@ogar:/home# sudo npm install ./Ogar
-
> utf-8-validate@1.1.0 install /home/node_modules/Ogar/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/home/node_modules/Ogar/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
make: g++: Command not found
validation.target.mk:85: recipe for target 'Release/obj.target/validation/src/validation.o' failed
make: *** [Release/obj.target/validation/src/validation.o] Error 127
make: Leaving directory '/home/node_modules/Ogar/node_modules/ws/node_modules/utf-8-validate/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-23-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node_modules/Ogar/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> bufferutil@1.1.0 install /home/node_modules/Ogar/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/home/node_modules/Ogar/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: g++: Command not found
bufferutil.target.mk:85: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 127
make: Leaving directory '/home/node_modules/Ogar/node_modules/ws/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-23-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node_modules/Ogar/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.1.0
Ogar@1.0.0 node_modules/Ogar
└── ws@0.7.2 (options@0.0.6, ultron@1.0.2)
```

**Comment by Spurlex** [comment]
Fixed by installing build essentials
