### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Eureka22** [vram4/Ogar#79]
After pulling the updates on Jun 19, server crush every time after started several seconds.

Here is the log:
[Game] Ogar - An open source Agar.io server implementation
[Game] Config not found... Generating new config
[Game] Listening on port 443
[Game] Current game mode is Free For All
>addbot 10
[Console] Added 10 player bots
>addbot 20
[Console] Added 20 player bots
>
TypeError: Object #<Cell> has no method 'onAutoMove'
    at GameServer.updateMoveEngine (/root/fun/Ogar/src/GameServer.js:466:19)
    at GameServer.mainLoop (/root/fun/Ogar/src/GameServer.js:274:18)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by vram4** [comment]
You need to update the entity folder
